apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-v3-lts-node
  namespace: argocd
spec:
  destination:
    namespace: cheese
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/my-chart
    repoURL: https://github.com/myorg/myrepo.git
    targetRevision: v0.0.5
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
